import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const { data, isLoading } = trpc.useQuery(["question.getMessages"]);

  return (
    <div>
      {sessionData && <p>Logged in as {sessionData?.user?.name}</p>}
      {isLoading ? (
        <p>Loading</p>
      ) : (
        data?.map((msg) => (
          <p key={msg.id}>
            {msg.message} - {msg.reactions}
          </p>
        ))
      )}
      <button
        className="px-4 py-2 border-2 border-blue-500 rounded-md"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthShowcase />
    </>
  );
};

export default Home;
